/*
 * Copyright (C) 1994-2018 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * PBS Pro is free software. You can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * PBS Pro is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * For a copy of the commercial license terms and conditions,
 * go to: (http://www.pbspro.com/UserArea/agreement.html)
 * or contact the Altair Legal Department.
 *
 * Altair’s dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of PBS Pro and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair’s trademarks, including but not limited to "PBS™",
 * "PBS Professional®", and "PBS Pro™" and Altair’s logos is subject to Altair's
 * trademark licensing policies.
 *
 */


/**
 * @file    db_pbs_job.c
 *
 * @brief
 *      Implementation of the job data access functions for postgres
 */

#include <pbs_config.h>   /* the master config generated by configure */
#include "pbs_db.h"
#include "db_aerospike.h"

/**
 *@brief
 *	Save (insert/update) a new/existing job
 *
 * @param[in]	conn - The connnection handle
 * @param[in]	obj  - The job object to save
 * @param[in]	savetype - PBS_UPDATE_DB_QUICK/PBS_UPDATE_DB_FULL/PBS_INSERT_DB
 *
 * @return      Error code
 * @retval	-1 - Execution of prepared statement failed
 * @retval	 0 - Success and > 0 rows were affected
 * @retval	 1 - Execution succeeded but statement did not affect any rows
 *
 */
int
pbs_db_save_job(void *conn, pbs_db_obj_info_t *obj, int savetype)
{
	pbs_db_job_info_t *pjob = obj->pbs_db_un.pbs_db_job;
	int numbins = 0;
	as_key key; /* jobid */
	as_integer  ji_state; /* Internal copy of state */
	as_integer  ji_substate; /* job sub-state */
	as_integer  ji_svrflags; /* server flags */
	as_integer  ji_stime; /* time job started execution */
	as_string   ji_queue; /* name of current queue */
	as_string   ji_destin; /* dest from qmove/route */
	as_integer  ji_un_type;
	as_integer  ji_exitstat; /* job exit status from MOM */
	as_integer  ji_quetime; /* time entered queue */
	as_integer  ji_rteretry; /* route retry time */
	as_integer  ji_fromsock; /* socket job coming over */
	as_integer  ji_fromaddr; /* host job coming from   */
	as_string   ji_jid;
	as_integer  ji_credtype;
	as_integer  ji_qrank;
	as_integer  ji_savetm;
	as_integer  ji_creattm;
	as_hashmap attrmap;
	as_map_policy map_policy;
	as_policy_operate op_policy;
	as_operations ops;
	as_error err;
	as_record* rec = NULL;
	aerospike *as = (aerospike *) conn;

	if (savetype & OBJ_SAVE_QS)
		numbins = 16;

	if (savetype & OBJ_SAVE_NEW)
		numbins++;  /* for createtm */
	if ((pjob->db_attr_list.attr_count > 0) || (savetype & OBJ_SAVE_NEW))
		numbins++;  /* for attributes */

	as_operations_inita(&ops, numbins);
	as_key_init_str(&key, g_namespace, "job", pjob->ji_jobid);

	if (savetype & OBJ_SAVE_QS) {
		as_integer_init(&ji_state, pjob->ji_state);
		as_operations_add_write(&ops, "ji_state", (as_bin_value*) &ji_state);
		as_integer_init(&ji_substate, pjob->ji_substate);
		as_operations_add_write(&ops, "ji_substate", (as_bin_value*) &ji_substate);
		as_integer_init(&ji_svrflags, pjob->ji_svrflags);
		as_operations_add_write(&ops, "ji_svrflags", (as_bin_value*) &ji_svrflags);
		as_integer_init(&ji_stime, pjob->ji_stime);
		as_operations_add_write(&ops, "ji_stime", (as_bin_value*) &ji_stime);
		as_string_init(&ji_queue, pjob->ji_queue, false);
		as_operations_add_write(&ops, "ji_queue", (as_bin_value*) &ji_queue);
		as_string_init(&ji_destin, pjob->ji_destin, false);
		as_operations_add_write(&ops, "ji_destin", (as_bin_value*) &ji_destin);
		as_integer_init(&ji_un_type, pjob->ji_un_type);
		as_operations_add_write(&ops, "ji_un_type", (as_bin_value*) &ji_un_type);
		as_integer_init(&ji_exitstat, pjob->ji_exitstat);
		as_operations_add_write(&ops, "ji_exitstat", (as_bin_value*) &ji_exitstat);
		as_integer_init(&ji_quetime, pjob->ji_quetime);
		as_operations_add_write(&ops, "ji_quetime", (as_bin_value*) &ji_quetime);
		as_integer_init(&ji_rteretry, pjob->ji_rteretry);
		as_operations_add_write(&ops, "ji_rteretry", (as_bin_value*) &ji_rteretry);
		as_integer_init(&ji_fromsock, pjob->ji_fromsock);
		as_operations_add_write(&ops, "ji_fromsock", (as_bin_value*) &ji_fromsock);
		as_integer_init(&ji_fromaddr, pjob->ji_fromaddr);
		as_operations_add_write(&ops, "ji_fromaddr", (as_bin_value*) &ji_fromaddr);
		as_string_init(&ji_jid, pjob->ji_jid, false);
		as_operations_add_write(&ops, "ji_jid", (as_bin_value*) &ji_jid);
		as_integer_init(&ji_credtype, pjob->ji_credtype);
		as_operations_add_write(&ops, "ji_credtype", (as_bin_value*) &ji_credtype);
		as_integer_init(&ji_qrank, pjob->ji_qrank);
		as_operations_add_write(&ops, "ji_qrank", (as_bin_value*) &ji_qrank);
		as_integer_init(&ji_savetm, db_time_now(0));
		as_operations_add_write(&ops, "ji_savetm", (as_bin_value*) &ji_savetm);
	}

	if (savetype & OBJ_SAVE_NEW) {
		as_integer_init(&ji_creattm, db_time_now(0));
		as_operations_add_write(&ops, "ji_creattm", (as_bin_value*) &ji_creattm);
	}

	if ((pjob->db_attr_list.attr_count > 0) || (savetype & OBJ_SAVE_NEW)) {
		if (convert_db_attr_list_to_asmap(&attrmap, &pjob->db_attr_list) < 0) 
			return -1;

		as_map_policy_init(&map_policy);
		as_operations_add_map_put_items(&ops, "attributes", &map_policy, (as_map*) &attrmap);
	}

	as_policy_operate_init(&op_policy);
	op_policy.key = AS_POLICY_KEY_SEND;
	
	if (aerospike_key_operate(as, &err, &op_policy, &key, &ops, &rec) != AEROSPIKE_OK) {
		char msg[4096];
		sprintf(msg, "aerospike_key_operate() returned %d - %s\n", err.code, err.message);
		db_set_error("Execution of save job", msg, NULL);
		as_operations_destroy(&ops);
		as_record_destroy(rec);
		return -1;
	}

	as_operations_destroy(&ops);
	as_record_destroy(rec);
	
	return 0;
}

static int
load_job(as_record* rec, pbs_db_job_info_t *pjob)
{
	as_map *attrmap;

	pjob->ji_state = as_record_get_int64(rec, "ji_state", INT64_MAX);
	pjob->ji_substate = as_record_get_int64(rec, "ji_substate", INT64_MAX);
	pjob->ji_svrflags = as_record_get_int64(rec, "ji_svrflags", INT64_MAX);
	pjob->ji_stime = as_record_get_int64(rec, "ji_stime", INT64_MAX);
	strcpy(pjob->ji_queue, as_record_get_str(rec, "ji_queue"));
	strcpy(pjob->ji_destin, as_record_get_str(rec, "ji_destin"));
	pjob->ji_un_type = as_record_get_int64(rec, "ji_un_type", INT64_MAX);
	pjob->ji_exitstat = as_record_get_int64(rec, "ji_exitstat", INT64_MAX);
	pjob->ji_quetime = as_record_get_int64(rec, "ji_quetime", INT64_MAX);
	pjob->ji_rteretry = as_record_get_int64(rec, "ji_rteretry", INT64_MAX);
	pjob->ji_fromsock = as_record_get_int64(rec, "ji_fromsock", INT64_MAX);
	pjob->ji_fromaddr = as_record_get_int64(rec, "ji_fromaddr", INT64_MAX);
	strcpy(pjob->ji_jid, as_record_get_str(rec, "ji_jid"));
	pjob->ji_credtype = as_record_get_int64(rec, "ji_credtype", INT64_MAX);
	pjob->ji_qrank = as_record_get_int64(rec, "ji_qrank", INT64_MAX);

	attrmap = as_record_get_map(rec, "attributes");
	if (convert_asmap_to_db_attr_list((as_hashmap *) attrmap, &pjob->db_attr_list) < 0) 
		return -1;

	return 0;
}

/**
 * @brief
 *	Load job data from the database
 *
 * @param[in]	conn - Connection handle
 * @param[in/out]obj  - Load job information into this object where
 *			jobid = obj->pbs_db_un.pbs_db_job->ji_jobid
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 * @retval	>1 - Number of attributes
 * @retval 	-2 -  Success but data same as old, so not loading data (but locking if lock requested)
 *
 */
int
pbs_db_load_job(void *conn, pbs_db_obj_info_t *obj)
{
	pbs_db_job_info_t *pjob = obj->pbs_db_un.pbs_db_job;
	int rc;
	as_key key; /* jobid */
	as_error err;
	as_record* p_rec = NULL;
	aerospike *as = (aerospike *) conn;

	as_key_init_str(&key, g_namespace, "job", pjob->ji_jobid);
	if (aerospike_key_get(as, &err, NULL, &key, &p_rec) != AEROSPIKE_OK) {
		char msg[4096];
		sprintf(msg, "aerospike_key_get() returned %d - %s\n", err.code, err.message);
		db_set_error("Execution of load job", msg, NULL);
		as_record_destroy(p_rec);
		return -1;
	}

	rc = load_job(p_rec, pjob);
	as_record_destroy(p_rec);
	
	return rc;
}

static
bool job_callback(const as_val *val, void* udata)
{
	pbs_db_obj_info_t obj;
	pbs_db_job_info_t dbjob;
	pbs_db_job_info_t *pjob = &dbjob;
	db_query_state_t *state = (db_query_state_t *) udata;
	as_record* rec = NULL;

	obj.pbs_db_obj_type = PBS_DB_JOB;
	obj.pbs_db_un.pbs_db_job = pjob;

	rec = as_record_fromval(val);
	if (!rec) return false;

	strcpy(pjob->ji_jobid, rec->key.value.string.value);
	load_job(rec, pjob);
	as_record_destroy(rec);
	state->query_cb(&obj, &state->count);

	pbs_db_reset_job(&obj);
	
	return true;
}

/**
 * @brief
 *	Find jobs
 *
 * @param[in]	conn - Connection handle
 * @param[out]  st   - The cursor state variable updated by this query
 * @param[in]	obj  - Information of job to be found
 * @param[in]	opts - Any other options (like flags, timestamp)
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 * @retval	 1 -  Success but no rows found
 *
 */
int
pbs_db_find_job(void *conn, void *st, pbs_db_obj_info_t *obj, pbs_db_query_options_t *opts)
{
	db_query_state_t *state = (db_query_state_t *) st;
	pbs_db_job_info_t *pdjob = obj->pbs_db_un.pbs_db_job;
	aerospike *as = (aerospike *) conn;
	as_query query;
	int savetm;
	as_error err;

	if (!state)
		return -1;

	as_query_init(&query, g_namespace, "job");
	if (opts != NULL && opts->flags == FIND_JOBS_BY_QUE) {
		as_query_where(&query, "ji_queue", as_string_equals(pdjob->ji_queue));
		// order by ji_qrank
	} else if (opts != NULL && opts->timestamp){
		as_query_where_inita(&query, 1);
		savetm = opts->timestamp;
		as_query_where(&query, "ji_savetm", as_integer_range(savetm, db_time_now(0)));
		// order by ji_qrank
	}

	state->row = 0;
	state->count = 0;

	if (aerospike_query_foreach(as, &err, NULL, &query, job_callback, state) != AEROSPIKE_OK) {
		char msg[4096];
		sprintf(msg,"aerospike_query_foreach() returned %d - %s", err.code, err.message);
		db_set_error("Execution of find job", msg, NULL);
		as_query_destroy(&query);
		return -1;
	}
	as_query_destroy(&query);

	return 0;
}


/**
 * @brief
 *	Delete the job from the database
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - Job information
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 * @retval	 1 -  Success but no rows deleted
 *
 */
int
pbs_db_delete_job(void *conn, pbs_db_obj_info_t *obj)
{
	pbs_db_job_info_t *pj = obj->pbs_db_un.pbs_db_job;
	as_key key; /* jobid */
	as_error err;
	aerospike *as = (aerospike *) conn;

	as_key_init_str(&key, g_namespace, "job", pj->ji_jobid);
	if (aerospike_key_remove(as, &err, NULL, &key) != AEROSPIKE_OK) {
		char msg[4096];
		sprintf(msg, "aerospike_key_remove() returned %d - %s\n", err.code, err.message);
		db_set_error("Execution of delete job", msg, NULL);
		return -1;
	}

	return 0;
}

/**
 * @brief
 *	Insert job script
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - Job script object
 * @param[in]	savetype - Just a place holder here. Maintained the same prototype as with
 * 		           the other database save functions since this is called through function pointer.
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
pbs_db_save_jobscr(void *conn, pbs_db_obj_info_t *obj, int savetype)
{
	pbs_db_jobscr_info_t *pscr = obj->pbs_db_un.pbs_db_jobscr;
	int numbins = 1;
	as_string script;
	aerospike *as = (aerospike *) conn;
	as_policy_operate op_policy;
	as_operations ops;
	as_error err;
	as_record* rec = NULL;
	as_key key;

	as_operations_inita(&ops, numbins);
	as_key_init_str(&key, g_namespace, "job_scr", pscr->ji_jobid);
	as_string_init(&script, (pscr->script)?pscr->script:"", false);
	as_operations_add_write(&ops, "script", (as_bin_value*) &script);

	if (aerospike_key_operate(as, &err, &op_policy, &key, &ops, &rec) != AEROSPIKE_OK) {
		char msg[4096];
		sprintf(msg, "aerospike_key_operate() returned %d - %s\n", err.code, err.message);
		db_set_error("Execution of save job_scr", msg, NULL);
		as_operations_destroy(&ops);
		as_record_destroy(rec);
		return -1;
	}

	as_operations_destroy(&ops);
	as_record_destroy(rec);
	return 0;
}

/**
 * @brief
 *	load job script
 *
 * @param[in]	  conn - Connection handle
 * @param[in/out] obj  - Job script is loaded into this object
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
pbs_db_load_jobscr(void *conn, pbs_db_obj_info_t *obj)
{
	pbs_db_jobscr_info_t *pscr = obj->pbs_db_un.pbs_db_jobscr;
	as_key key; /* jobid */
	as_error err;
	as_record* p_rec = NULL;
	char *script = NULL;
	aerospike *as = (aerospike *) conn;

	as_key_init_str(&key, g_namespace, "job_scr", pscr->ji_jobid);
	if (aerospike_key_get(as, &err, NULL, &key, &p_rec) != AEROSPIKE_OK) {
		char msg[4096];
		sprintf(msg, "aerospike_key_get() returned %d - %s\n", err.code, err.message);
		db_set_error("Execution of load job_scr", msg, NULL);
		as_record_destroy(p_rec);
		return -1;
	}

	script = as_record_get_str(p_rec, "script");
	pscr->script = strdup(script);
	as_record_destroy(p_rec);
	
	return 0;
}

/**
 * @brief
 *	Deletes attributes of a job
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - Job information
 * @param[in]	obj_id  - Job id
 * @param[in]	attr_list - List of attributes
 *
 * @return      Error code
 * @retval	 0 - Success
 * @retval	-1 - On Failure
 *
 */
int
pbs_db_del_attr_job(void *conn, void *obj_id, pbs_db_attr_list_t *attr_list)
{
	as_string attr;
	int numbins = 1;
	aerospike *as = (aerospike *) conn;
	as_policy_operate op_policy;
	as_operations ops;
	as_error err;
	as_record* rec = NULL;
	as_key key;

	as_operations_inita(&ops, numbins);
	as_key_init_str(&key, g_namespace, "job", obj_id);
	as_string_init(&attr, "", false);
	as_operations_add_write(&ops, "attributes", (as_bin_value*) &attr);

	if (aerospike_key_operate(as, &err, &op_policy, &key, &ops, &rec) != AEROSPIKE_OK) {
		char msg[4096];
		sprintf(msg, "aerospike_key_operate() returned %d - %s\n", err.code, err.message);
		db_set_error("Execution of delete job attrs", msg, NULL);
		as_operations_destroy(&ops);
		as_record_destroy(rec);
		return -1;
	}

	as_operations_destroy(&ops);
	as_record_destroy(rec);
	return 0;
}

/**
 * @brief
 *	Frees allocate memory of an Object
 *
 * @param[in]	obj - pbs_db_obj_info_t containing the DB object
 *
 * @return      None
 *
 */
void
pbs_db_reset_job(pbs_db_obj_info_t *obj)
{
	obj->pbs_db_un.pbs_db_job->ji_jobid[0] = '\0';
}
