/*
 * Copyright (C) 1994-2021 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of both the OpenPBS software ("OpenPBS")
 * and the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * OpenPBS is free software. You can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * OpenPBS is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * PBS Pro is commercially licensed software that shares a common core with
 * the OpenPBS software.  For a copy of the commercial license terms and
 * conditions, go to: (http://www.pbspro.com/agreement.html) or contact the
 * Altair Legal Department.
 *
 * Altair's dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of OpenPBS and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair's trademarks, including but not limited to "PBS™",
 * "OpenPBS®", "PBS Professional®", and "PBS Pro™" and Altair's logos is
 * subject to Altair's trademark licensing policies.
 */



/**
 *
 * @brief
 *      Implementation of the node data access functions for postgres
 */

#include <pbs_config.h>   /* the master config generated by configure */
#include "pbs_db.h"
#include "db_aerospike.h"


/**
 * @brief
 *	Insert node data into the database
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - Information of node to be inserted
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
pbs_db_save_node(void *conn, pbs_db_obj_info_t *obj, int savetype)
{
	pbs_db_node_info_t *pnd = obj->pbs_db_un.pbs_db_node;
	int numbins;
	as_key key;
	as_integer  nd_index;
	as_integer  mom_modtime;
	as_string   nd_hostname;
	as_integer  nd_state;
	as_integer  nd_ntype;
	as_string   nd_pque;
	as_integer  nd_savetm;
	as_integer  nd_creattm;
	as_hashmap attrmap;
	as_map_policy map_policy;
	as_policy_operate op_policy;
	as_operations ops;
	as_error err;
	as_record* rec = NULL;
	aerospike *as = (aerospike *) conn;

	if (savetype & OBJ_SAVE_QS) {
		numbins = 7;
	} else {
		numbins = 1;
	}
	if (savetype & OBJ_SAVE_NEW)
		numbins++;  /* for createtm */

	as_operations_inita(&ops, numbins);
	as_key_init_str(&key, g_namespace, "node", pnd->nd_name);
	
	if (savetype & OBJ_SAVE_QS) {
		as_integer_init(&nd_index, pnd->nd_index);
		as_operations_add_write(&ops, "nd_index", (as_bin_value*) &nd_index);
		as_integer_init(&mom_modtime, pnd->mom_modtime);
		as_operations_add_write(&ops, "mom_modtime", (as_bin_value*) &nd_index);
		as_string_init(&nd_hostname, pnd->nd_hostname, false);
		as_operations_add_write(&ops, "nd_hostname", (as_bin_value*) &nd_hostname);
		as_integer_init(&nd_state, pnd->nd_state);
		as_operations_add_write(&ops, "nd_state", (as_bin_value*) &nd_state);
		as_integer_init(&nd_ntype, pnd->nd_ntype);
		as_operations_add_write(&ops, "nd_ntype", (as_bin_value*) &nd_ntype);
		as_string_init(&nd_pque, pnd->nd_pque, false);
		as_operations_add_write(&ops, "nd_pque", (as_bin_value*) &nd_pque);
		as_integer_init(&nd_savetm, db_time_now(0));
		as_operations_add_write(&ops, "nd_savetm", (as_bin_value*) &nd_savetm);
	}

	if (savetype & OBJ_SAVE_NEW) {
		as_integer_init(&nd_creattm, db_time_now(0));
		as_operations_add_write(&ops, "nd_creattm", (as_bin_value*) &nd_creattm);
	}

	if ((pnd->db_attr_list.attr_count > 0) || (savetype & OBJ_SAVE_NEW)) {
		if (convert_db_attr_list_to_asmap(&attrmap, &pnd->db_attr_list) < 0) 
			return -1;

		as_map_policy_init(&map_policy);
		as_operations_add_map_put_items(&ops, "attributes", &map_policy, (as_map*) &attrmap);
	}

	as_policy_operate_init(&op_policy);
	op_policy.key = AS_POLICY_KEY_SEND;
	if (aerospike_key_operate(as, &err, &op_policy, &key, &ops, &rec) != AEROSPIKE_OK) {
		char msg[4096];
		sprintf(msg, "aerospike_key_operate() returned %d - %s\n", err.code, err.message);
		db_set_error("Execution of save node", msg, NULL);
		as_operations_destroy(&ops);
		as_record_destroy(rec);
		return -1;
	}

	as_operations_destroy(&ops);
	as_record_destroy(rec);
	
	return 0;
}

/**
 * @brief
 *	Load node data from the row into the node object
 *
 * @param[in]	res - Resultset from a earlier query
 * @param[in]	pnd  - Node object to load data into
 * @param[in]	row - The current row to load within the resultset
 *
 * @return      Error code
 * @retval	-1 - On Error
 * @retval	 0 - On Success
 * @retval	>1 - Number of attributes
 *
 */
static int
load_node(as_record* rec, pbs_db_node_info_t *pnd)
{
	as_map *attrmap;
	pnd->nd_index = as_record_get_int64(rec, "nd_index", INT64_MAX);
	pnd->mom_modtime = as_record_get_int64(rec, "mom_modtime", INT64_MAX);
	strcpy(pnd->nd_hostname, as_record_get_str(rec, "nd_hostname"));
	pnd->nd_state = as_record_get_int64(rec, "nd_state", INT64_MAX);
	pnd->nd_ntype = as_record_get_int64(rec, "nd_ntype", INT64_MAX);
	strcpy(pnd->nd_pque, as_record_get_str(rec, "nd_pque"));

	attrmap = as_record_get_map(rec, "attributes");
	if (convert_asmap_to_db_attr_list((as_hashmap *) attrmap, &pnd->db_attr_list) < 0) 
		return -1;

	return 0;
}

/**
 * @brief
 *	Load node data from the database
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - Load node information into this object
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 * @retval	 1 -  Success but no rows loaded
 *
 */
int
pbs_db_load_node(void *conn, pbs_db_obj_info_t *obj)
{
	pbs_db_node_info_t *pnd = obj->pbs_db_un.pbs_db_node;
	int rc;
	as_key key; /* jobid */
	as_error err;
	as_record* p_rec = NULL;
	aerospike *as = (aerospike *) conn;

	as_key_init_str(&key, g_namespace, "node", pnd->nd_name);
	if (aerospike_key_get(as, &err, NULL, &key, &p_rec) != AEROSPIKE_OK) {
		char msg[4096];
		sprintf(msg, "aerospike_key_get() returned %d - %s\n", err.code, err.message);
		db_set_error("Execution of load node", msg, NULL);
		as_record_destroy(p_rec);
		return -1;
	}

	rc = load_node(p_rec, pnd);
	as_record_destroy(p_rec);

	return rc;
}

static
bool node_callback(const as_val *val, void* udata)
{
	pbs_db_obj_info_t obj;
	pbs_db_node_info_t dbnd;
	pbs_db_node_info_t *pnd = &dbnd;
	db_query_state_t *state = (db_query_state_t *) udata;
	as_record* rec = NULL;

	obj.pbs_db_obj_type = PBS_DB_NODE;
	obj.pbs_db_un.pbs_db_node = pnd;

	rec = as_record_fromval(val);
	if (!rec) return false;

	strcpy(pnd->nd_name, rec->key.value.string.value);
	load_node(rec, pnd);
	as_record_destroy(rec);
	state->query_cb(&obj, &state->count);
	
	return true;
}

/**
 * @brief
 *	Find nodes
 *
 * @param[in]	conn - Connection handle
 * @param[in]	st   - The cursor state variable updated by this query
 * @param[in]	obj  - Information of node to be found
 * @param[in]	opts - Any other options (like flags, timestamp)
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 * @retval	 1 - Success, but no rows found
 *
 */
int
pbs_db_find_node(void *conn, void *st, pbs_db_obj_info_t *obj,
	pbs_db_query_options_t *opts)
{
	int rc;
	db_query_state_t *state = (db_query_state_t *) st;
	aerospike *as = (aerospike *) conn;
	as_query query;
	as_error err;

	if (!state)
		return -1;

	as_query_init(&query, g_namespace, "node");
	// write query with: from pbs.node order by nd_index, nd_creattm

	state->row = 0;
	state->count = 0;
	rc = aerospike_query_foreach(as, &err, NULL, &query, node_callback, state);
	if (rc == AEROSPIKE_ERR_RECORD_NOT_FOUND) {
		as_query_destroy(&query);
		return 1;
	}
	if (rc != AEROSPIKE_OK) {
		char msg[4096];
		sprintf(msg,"aerospike_query_foreach() returned %d - %s", err.code, err.message);
		db_set_error("Execution of find node", msg, NULL);
		as_query_destroy(&query);
		return -1;
	}
	as_query_destroy(&query);

	return 0;
}


/**
 * @brief
 *	Delete the node from the database
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - Node information
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
pbs_db_delete_node(void *conn, pbs_db_obj_info_t *obj)
{
	pbs_db_node_info_t *pnd = obj->pbs_db_un.pbs_db_node;
	as_key key;
	as_error err;
	aerospike *as = (aerospike *) conn;

	as_key_init_str(&key, g_namespace, "node", pnd->nd_name);
	if (aerospike_key_remove(as, &err, NULL, &key) != AEROSPIKE_OK) {
		char msg[4096];
		sprintf(msg, "aerospike_key_remove() returned %d - %s\n", err.code, err.message);
		db_set_error("Execution of delete node", msg, NULL);
		return -1;
	}

	return 0;
}

/**
 * @brief
 *	Deletes attributes of a node
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj_id  - Node id
 * @param[in]	attr_list - List of attributes
 *
 * @return      Error code
 * @retval	 0 - Success
 * @retval	-1 - On Failure
 *
 */
int
pbs_db_del_attr_node(void *conn, void *obj_id, pbs_db_attr_list_t *attr_list)
{
	as_string attr;
	int numbins = 1;
	aerospike *as = (aerospike *) conn;
	as_policy_operate op_policy;
	as_operations ops;
	as_error err;
	as_record* rec = NULL;
	as_key key;

	as_operations_inita(&ops, numbins);
	as_key_init_str(&key, g_namespace, "node", obj_id);
	as_string_init(&attr, "", false);
	as_operations_add_write(&ops, "attributes", (as_bin_value*) &attr);

	if (aerospike_key_operate(as, &err, &op_policy, &key, &ops, &rec) != AEROSPIKE_OK) {
		char msg[4096];
		sprintf(msg, "aerospike_key_operate() returned %d - %s\n", err.code, err.message);
		db_set_error("Execution of delete node attrs", msg, NULL);
		as_operations_destroy(&ops);
		as_record_destroy(rec);
		return -1;
	}

	as_operations_destroy(&ops);
	as_record_destroy(rec);
	return 0;
}


/**
 * @brief
 *	Insert mominfo_time into the database
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - Information of node to be inserted
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
pbs_db_save_mominfo_tm(void *conn, pbs_db_obj_info_t *obj, int savetype)
{
	pbs_db_mominfo_time_t *pmi = obj->pbs_db_un.pbs_db_mominfo_tm;
	int numbins = 2;
	as_integer  mit_time;
	as_integer  mit_gen;
	aerospike *as = (aerospike *) conn;
	as_policy_operate op_policy;
	as_operations ops;
	as_error err;
	as_record* rec = NULL;
	as_key key;

	as_operations_inita(&ops, numbins);
	as_key_init_str(&key, g_namespace, "mominfo_time", "mominfo_time");
	as_integer_init(&mit_time, pmi->mit_time);
	as_operations_add_write(&ops, "mit_time", (as_bin_value*) &mit_time);
	as_integer_init(&mit_gen, pmi->mit_gen);
	as_operations_add_write(&ops, "mit_time", (as_bin_value*) &mit_gen);

	as_policy_operate_init(&op_policy);
	op_policy.key = AS_POLICY_KEY_SEND;
	if (aerospike_key_operate(as, &err, &op_policy, &key, &ops, &rec) != AEROSPIKE_OK) {
		char msg[4096];
		sprintf(msg, "aerospike_key_operate() returned %d - %s\n", err.code, err.message);
		db_set_error("Execution of save mominfo_time", msg, NULL);
		as_operations_destroy(&ops);
		as_record_destroy(rec);
		return -1;
	}

	as_operations_destroy(&ops);
	as_record_destroy(rec);
	return 0;
}

/**
 * @brief
 *	Load node mominfo_time from the database
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - Load node information into this object
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 * @retval	 1 -  Success but no rows loaded
 *
 */
int
pbs_db_load_mominfo_tm(void *conn, pbs_db_obj_info_t *obj)
{
	pbs_db_mominfo_time_t *pmi = obj->pbs_db_un.pbs_db_mominfo_tm;
	static int mit_time_fnum = -1;
	static int mit_gen_fnum = -1;
	as_key key;
	as_error err;
	as_record* p_rec = NULL;
	aerospike *as = (aerospike *) conn;
	int rc;

	as_key_init_str(&key, g_namespace, "mominfo_time", "mominfo_time");
	rc = aerospike_key_get(as, &err, NULL, &key, &p_rec);
	if (rc != AEROSPIKE_OK) {
		if (rc == AEROSPIKE_ERR_RECORD_NOT_FOUND) {
			mit_time_fnum = pmi->mit_time;
			mit_gen_fnum = pmi->mit_gen;
			as_record_destroy(p_rec);
			return 1;
		}
		char msg[4096];
		sprintf(msg, "aerospike_key_get() returned %d - %s\n", err.code, err.message);
		db_set_error("Execution of load mominfo_time", msg, NULL);
		as_record_destroy(p_rec);
		return -1;
	}

	if (mit_time_fnum == -1 || mit_gen_fnum == -1) {
		mit_time_fnum = as_record_get_int64(p_rec, "mit_time", INT64_MAX);
		mit_gen_fnum = as_record_get_int64(p_rec, "mit_gen", INT64_MAX);
	}
	pmi->mit_time = mit_time_fnum;
	pmi->mit_gen = mit_gen_fnum;
	as_record_destroy(p_rec);

	return 0;
}
