/*
 * Copyright (C) 1994-2018 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * PBS Pro is free software. You can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * PBS Pro is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * For a copy of the commercial license terms and conditions,
 * go to: (http://www.pbspro.com/UserArea/agreement.html)
 * or contact the Altair Legal Department.
 *
 * Altair’s dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of PBS Pro and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair’s trademarks, including but not limited to "PBS™",
 * "PBS Professional®", and "PBS Pro™" and Altair’s logos is subject to Altair's
 * trademark licensing policies.
 *
 */


/**
 * @file    db_pbs_svr.c
 *
 * @brief
 *      Implementation of the svr data access functions for postgres
 */

#include <pbs_config.h>   /* the master config generated by configure */
#include "pbs_db.h"
#include "db_aerospike.h"

/**
 *@brief
 *	Save (insert/update) a new/existing svr
 *
 * @param[in]	conn - The connnection handle
 * @param[in]	obj  - The svr object to save
 * @param[in]	savetype - PBS_UPDATE_DB_QUICK/PBS_UPDATE_DB_FULL/PBS_INSERT_DB
 *
 * @return      Error code
 * @retval	-1 - Execution of prepared statement failed
 * @retval	 0 - Success and > 0 rows were affected
 * @retval	 1 - Execution succeeded but statement did not affect any rows
 *
 */
int
pbs_db_save_svr(void *conn, pbs_db_obj_info_t *obj, int savetype)
{
	pbs_db_svr_info_t *psvr = obj->pbs_db_un.pbs_db_svr;
	int numbins = 2; /* default minimum */
	
	as_key key;
	as_integer  sv_jobidnumber;
	as_integer  sv_savetm;
	as_integer  sv_creattm;
	as_hashmap attrmap;
	as_map_policy map_policy;
	as_policy_operate op_policy;
	as_operations ops;
	as_error err;
	as_record* rec = NULL;
	aerospike *as = (aerospike *) conn;

	if (savetype & OBJ_SAVE_NEW)
		numbins++;  /* for createtm */
	if ((psvr->db_attr_list.attr_count > 0) || (savetype & OBJ_SAVE_NEW))
		numbins++;  /* for attributes */

	as_operations_inita(&ops, numbins);
	as_key_init_str(&key, g_namespace, "server", "server");

	as_integer_init(&sv_jobidnumber, psvr->sv_jobidnumber);
	as_operations_add_write(&ops, "sv_jobidnumber", (as_bin_value*) &sv_jobidnumber);
	as_integer_init(&sv_savetm, db_time_now(0));
	as_operations_add_write(&ops, "sv_savetm", (as_bin_value*) &sv_savetm);

	if (savetype & OBJ_SAVE_NEW) {
		as_integer_init(&sv_creattm, db_time_now(0));
		as_operations_add_write(&ops, "sv_creattm", (as_bin_value*) &sv_creattm);
	}
	
	if ((psvr->db_attr_list.attr_count > 0) || (savetype & OBJ_SAVE_NEW)) {
		if (convert_db_attr_list_to_asmap(&attrmap, &psvr->db_attr_list) < 0)
			return -1;

		as_map_policy_init(&map_policy);
		as_operations_add_map_put_items(&ops, "attributes", &map_policy, (as_map*) &attrmap);
	}

	as_policy_operate_init(&op_policy);
	op_policy.key = AS_POLICY_KEY_SEND;
	
	if (aerospike_key_operate(as, &err, &op_policy, &key, &ops, &rec) != AEROSPIKE_OK) {
		char msg[4096];
		sprintf(msg, "aerospike_key_operate() returned %d - %s\n", err.code, err.message);
		db_set_error("Execution of save server", msg, NULL);
		as_operations_destroy(&ops);
		as_record_destroy(rec);
		return -1;
	}

	as_operations_destroy(&ops);
	as_record_destroy(rec);
	
	return 0;
}

int
load_svr(as_record* rec, pbs_db_svr_info_t *psvr)
{
	as_map *attrmap;
	
	psvr->sv_jobidnumber = as_record_get_int64(rec, "sv_jobidnumber", INT64_MAX);
	attrmap = as_record_get_map(rec, "attributes");
	if (convert_asmap_to_db_attr_list((as_hashmap *) attrmap, &psvr->db_attr_list) < 0) 
		return -1;

	return 0;
}

/**
 * @brief
 *	Load svr data from the database
 *
 * @param[in]	conn - Connection handle
 * @param[in/out]obj  - Load svr information into this object
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 * @retval	>1 - Number of attributes
 * @retval 	-2 -  Success but data same as old, so not loading data (but locking if lock requested)
 *
 */
int
pbs_db_load_svr(void *conn, pbs_db_obj_info_t *obj)
{
	pbs_db_svr_info_t *psvr = obj->pbs_db_un.pbs_db_svr;
	as_key key;
	as_error err;
	as_record* p_rec = NULL;
	aerospike *as = (aerospike *) conn;

	as_key_init_str(&key, g_namespace, "server", "server");
	if (aerospike_key_get(as, &err, NULL, &key, &p_rec) != AEROSPIKE_OK) {
		char msg[4096];
		sprintf(msg, "aerospike_key_get() returned %d - %s\n", err.code, err.message);
		db_set_error("Execution of load server", msg, NULL);
		as_record_destroy(p_rec);
		return -1;
	}

	load_svr(p_rec, psvr);
	as_record_destroy(p_rec);
	
	return 0;
}

/**
 * @brief
 *	Deletes attributes of a svr
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - svr information
 * @param[in]	obj_id  - svr name + partition id
 * @param[in]	attr_list - List of attributes
 *
 * @return      Error code
 * @retval	 0 - Success
 * @retval	-1 - On Failure
 *
 */
int
pbs_db_del_attr_svr(void *conn, void *obj_id, pbs_db_attr_list_t *attr_list)
{
	as_string attr;
	int numbins = 1;
	aerospike *as = (aerospike *) conn;
	as_policy_operate op_policy;
	as_operations ops;
	as_error err;
	as_record* rec = NULL;
	as_key key;

	as_operations_inita(&ops, numbins);
	as_key_init_str(&key, g_namespace, "server", "server");
	as_string_init(&attr, "", false);
	as_operations_add_write(&ops, "attributes", (as_bin_value*) &attr);

	if (aerospike_key_operate(as, &err, &op_policy, &key, &ops, &rec) != AEROSPIKE_OK) {
		char msg[4096];
		sprintf(msg, "aerospike_key_operate() returned %d - %s\n", err.code, err.message);
		db_set_error("Execution of delete server attrs", msg, NULL);
		as_operations_destroy(&ops);
		as_record_destroy(rec);
		return -1;
	}

	as_operations_destroy(&ops);
	as_record_destroy(rec);
	return 0;
}

